### ISSUE TITLE
Error NullPointer ExpedientHelper.omplirPermisosExpedients en els logs

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1078]
S'ha detectat en els logs una excepció per NullPointerException que s'ha de revisar i arreglar:

`2017-06-14 09:00:58,830 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/helium].[helium]] (http-10.215.9.183-18080-1
9) Servlet.service() para servlet helium lanzó excepción
java.lang.NullPointerException
        at net.conselldemallorca.helium.core.helper.ExpedientHelper.omplirPermisosExpedients(ExpedientHelper.java:801)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper.omplirPermisosExpedient(ExpedientHelper.java:811)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper$$FastClassBySpringCGLIB$$bd587714.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper$$EnhancerBySpringCGLIB$$488b35d6.omplirPermisosExpedient(<generated>)
        at net.conselldemallorca.helium.v3.core.service.ExpedientServiceImpl.findAmbId(ExpedientServiceImpl.java:510)
        at sun.reflect.GeneratedMethodAccessor2026.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:55)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
        at com.sun.proxy.$Proxy366.findAmbId(Unknown Source)
        at net.conselldemallorca.helium.webapp.v3.controller.BaseExpedientController.mostrarInformacioExpedientPerPipella(BaseExpedientContr
oller.java:38)
        at net.conselldemallorca.helium.webapp.v3.controller.ExpedientV3Controller.info(ExpedientV3Controller.java:70)
        at sun.reflect.GeneratedMethodAccessor2190.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod
.java:104)`

**Comment by josepg-limit** [comment]
Finalment no sembla que es repeteixi.

**Comment by josepg-limit** [comment]
Es demanen i revisen els logs del 27/06/2017 i no es repeteix l'error, es tanca la issue sense codi generat.
