### ISSUE TITLE
Error en la reindexació després d'un canvi d'estat a l'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1079]
S'ha detectat un error quan es canvia un estat dins d'una tasca d'un expedient i la reindexació falla. La reindexació a més hauria de ser asíncrona. 
 Els logs de l'error en qüestió són els següents:

```
2017-06-14 09:34:48,319 ERROR [net.conselldemallorca.helium.core.helperv26.LuceneHelper] Error actualitzant l'índex per l'expedient 219905
org.springmodules.lucene.index.LuceneIndexAccessException: Error during updating a document.; nested exception is org.springmodules.lucene.i
ndex.LuceneIndexAccessException: The identifier returns more than one document.
        at org.springmodules.lucene.index.core.DefaultLuceneIndexTemplate.updateDocument(DefaultLuceneIndexTemplate.java:356)
        at org.springmodules.lucene.index.core.DefaultLuceneIndexTemplate.updateDocument(DefaultLuceneIndexTemplate.java:343)
        at net.conselldemallorca.helium.core.helperv26.LuceneHelper.updateExpedientCamps(LuceneHelper.java:223)
        at net.conselldemallorca.helium.core.helperv26.LuceneHelper.updateExpedientCapsalera(LuceneHelper.java:199)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper.update(ExpedientHelper.java:515)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper$$FastClassBySpringCGLIB$$bd587714.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:629)
        at net.conselldemallorca.helium.core.helper.ExpedientHelper$$EnhancerBySpringCGLIB$$7fc441ae.update(<generated>)
        at net.conselldemallorca.helium.core.helper.Jbpm3HeliumHelper.expedientModificarEstat(Jbpm3HeliumHelper.java:457)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
        at com.sun.proxy.$Proxy384.expedientModificarEstat(Unknown Source)
        at net.conselldemallorca.helium.jbpm3.handlers.ExpedientEstatModificarHandler.execute(ExpedientEstatModificarHandler.java:39)
        at es.caib.sisdepen.helium.handlers.ActualizaSdpExpEstadoHandler.execute(ActualizaSdpExpEstadoHandler.java:93)
        at org.jbpm.graph.def.Action.execute(Action.java:197)
        at org.jbpm.graph.def.GraphElement.executeAction(GraphElement.java:307)
        at org.jbpm.graph.def.GraphElement.executeActions(GraphElement.java:248)
        at org.jbpm.graph.def.GraphElement.fireAndPropagateEvent(GraphElement.java:220)
        at org.jbpm.graph.def.GraphElement.fireEvent(GraphElement.java:203)
        at org.jbpm.graph.def.Node.enter(Node.java:371) 
```

**Comment by josepg-limit** [comment]
Es modifica per comprovar si el tipus d'expedient té la indexació
asíncrona o síncrona quan es modifica l'expedient en comptes de que
sigui sempre síncron.
La excepció està provocada per una consulta de Lucene que troba més d'un resultat per al seu identificador. S'ha d'investigar què pot haver causat el problema, però es pot provar de reindexar un expedient amb la opció "Reindexar l'expedient" dins de la gestió de l'expedient.
