### ISSUE TITLE
Error Ajax en expedient o tasques degut a Error 500 a primera hora

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1094]
Durant els darrers dies a primera hora (3 vegades), no consecutius, s'ha produït l'error 500 + error d'AJAX quan s'ha accedeix a les tasques o a gestionar. Una vegada reiniciat el servidor ja funciona correctament.
En els logs apareix el següent error:
`2017-07-20 08:32:07,946 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/helium].[helium]] (http-10.215.9.183-18080-17) Servlet.service() para servlet helium lanzó excepción
java.lang.NullPointerException
    at net.conselldemallorca.helium.core.helper.ExpedientHelper.omplirPermisosExpedients(ExpedientHelper.java:803)
    at net.conselldemallorca.helium.core.helper.ExpedientHelper.omplirPermisosExpedient(ExpedientHelper.java:813)
    at net.conselldemallorca.helium.core.helper.ExpedientHelper$$FastClassBySpringCGLIB$$bd587714.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)`

**Comment by josepg-limit** [comment]
Es modifica el codi on falla enregistrant un error per identificar quan falla i es rectifica la propietat expedientDto.tipus per a que pugui continuar executant-se.
