### ISSUE TITLE
Error generant informe després de canviar arxiu d'informe consulta

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1131]
Es reporta que després de modificar un arxiu per a generar un informe de consulta llavors en generar l'informe es captura el següent error:

`2017-10-20 12:35:14,226 ERROR [org.apache.commons.digester.Digester] (http-10.215.9.184-58080-23) Parse Error at line 4 column 490: cvc-complex-type.3.2.2: Attribute 'uuid' is not allowed to appear in element 'jasperReport'.
org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 490; cvc-complex-type.3.2.2: Attribute 'uuid' is not allowed to appear in element 'jasperReport'.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.processAttributes(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1647)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:241)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:228)
	at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:216)
	at net.sf.jasperreports.engine.JasperCompileManager.compileReport(JasperCompileManager.java:199)
	at net.conselldemallorca.helium.webapp.mvc.JasperReportsView.render(JasperReportsView.java:74)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1216)`

**Comment by josepg-limit** [comment]
L'error es deu a que els editors que generen reports superiors a la versió 4.5 de Jasper Reports posen l'atribut uuid dins l'XML, s'ha de configurar l'editor per a que mantingui compatibilitat.
