### ISSUE TITLE
Error migrant expedient a l'arxiu

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1280]
Es reporta que en alguns casos de migració d'expedients a l'arxiu s'obté una error com el següent:
![image](https://user-images.githubusercontent.com/17267008/53955236-bd075a00-40d8-11e9-9ce1-fcfc1ff59cfa.png)

En els logs apareix el següent error:
`2019-03-07 11:32:09,007 ERROR [net.conselldemallorca.helium.v3.core.api.service.ExecucioMassivaService] (myScheduler-7) Error al executar la acció massiva (expedientTipusId=3050, dataInici=Thu Mar 07 11:31:08 CET 2019, expedient=58101, acció=net.conselldemallorca.helium.core.model.hibernate.ExecucioMassivaExpedient@8a3979d6
net.conselldemallorca.helium.v3.core.api.exception.SistemaExternException:  ===> Error en la comunicació amb el sistema extern 'No s'ha pogut esborrar l'expedient a l'arxiu: [HTTP_400, COD_099] No ha sido informado en la petición del servicio el identificador del expediente o subexpediente a eliminar.': ArxiuCaibException: [HTTP_400, COD_099] No ha sido informado en la petición del servicio el identificador del expediente o subexpediente a eliminar.
    at net.conselldemallorca.helium.v3.core.api.exception.SistemaExternException.tractarSistemaExternException(SistemaExternException.java:108)
    at net.conselldemallorca.helium.core.helper.PluginHelper.tractarExcepcioEnSistemaExtern(PluginHelper.java:3883)
    at net.conselldemallorca.helium.core.helper.PluginHelper.arxiuExpedientEsborrar(PluginHelper.java:2252)
    at net.conselldemallorca.helium.v3.core.service.ExecucioMassivaServiceImpl.migrarExpedient(ExecucioMassivaServiceImpl.java:1587)
    at net.conselldemallorca.helium.v3.core.service.ExecucioMassivaServiceImpl.executarExecucioMassiva(ExecucioMassivaServiceImpl.java:838)
    at sun.reflect.GeneratedMethodAccessor1614.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
    at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
    at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
    at com.sun.proxy.$Proxy405.executarExecucioMassiva(Unknown Source)
    at net.conselldemallorca.helium.v3.core.service.TascaProgramadaServiceImpl.comprovarExecucionsMassives(TascaProgramadaServiceImpl.java:83)
    at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:64)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:53)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: es.caib.plugins.arxiu.caib.ArxiuCaibException: [HTTP_400, COD_099] No ha sido informado en la petición del servicio el identificador del expediente o subexpediente a eliminar.
    at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarExcepcioJson(ArxiuCaibClient.java:244)
    at es.caib.plugins.arxiu.caib.ArxiuCaibClient.generarEnviarPeticio(ArxiuCaibClient.java:138)
    at es.caib.plugins.arxiu.caib.ArxiuPluginCaib.expedientEsborrar(ArxiuPluginCaib.java:259)
    at net.conselldemallorca.helium.core.helper.PluginHelper.arxiuExpedientEsborrar(PluginHelper.java:2235)
    ... 27 more`

 S'ha de revisar per què intenta esborrar un expedient dins l'Arxiu i perquè falla l'esborrat d'expedients dins l'Arxiu (falta informar l'identificador).

**Comment by josepg-limit** [comment]
L'error capturat es deu a que s'intenta esborrar l'expedient a l'arxiu després d'un error en la migració i és aquest error el que s'acaba reportant. De moment s'arregla per a que si falla la migració aparegui l'error real en comptes de l'excepció "RollbackException".
