### ISSUE TITLE
Error donant d'alta variables al tipus d'expedient

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1318]
Es reporta un error en el que no es poden donar d'alta variables en el disseny del tipus d'expedient a l'entorn de pre producció. L'error en els logs és el següent:
```
2019-07-16 14:41:57,434 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/helium].[helium]] (http-10.215.9.184-58080-2) Servlet.service() para servlet helium lanzó excepción
    java.lang.NoSuchMethodError: net.conselldemallorca.helium.core.model.hibernate.Camp.setDominiIntern(Z)V
        at net.conselldemallorca.helium.v3.core.service.CampServiceImpl.create(CampServiceImpl.java:137)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
S'ha provat la versió anterior i l'error ha desaparegut de l'entorn de pre producció.

**Comment by josepg-limit** [comment]
Es modifica la propietat dominiIntern del Camp per a evitar aquest tipus d'error.
