### ISSUE TITLE
Error NullPointerException en la migració d'expedients a l'Arxiu

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#1416]
Durant la migració d'expedients a l'Arxiu per execucions massives s'ha reportat un error de NullPointerException que s'ha de reproduir, revisar i corregir.

```
2020-10-08 00:03:43,755 ERROR [net.conselldemallorca.helium.v3.core.api.service.ExecucioMassivaService] OPERACIO:1824129. No s'ha pogut MIGRAR
net.conselldemallorca.helium.v3.core.api.exception.TramitacioException:  ===> S'ha produït un error de tramitació. Error migrant l'expedient XXX
 a l'arxiu: null: null entornID: 150. entornCodi: EXSANCI. entornNom: Sistema corporatiu EXSANCI-TAXES. expedientID: 408961. expedientTitol: XXX
. expedientNumero: XXX. expedientTipusID: 563. expedientTipusCodi: EXSANCI_EM. expedientTipusNom: Sancionadors Emergències.
	at net.conselldemallorca.helium.v3.core.service.ExpedientServiceImpl.migrarArxiu(ExpedientServiceImpl.java:1257)
	at sun.reflect.GeneratedMethodAccessor7830.invoke(Unknown Source)
...
Caused by: java.lang.NullPointerException
	at net.conselldemallorca.helium.core.helper.ExpedientHelper.migrarArxiu(ExpedientHelper.java:809)
	at net.conselldemallorca.helium.core.helper.ExpedientHelper$$FastClassBySpringCGLIB$$bd587714.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)

```

**Comment by josepg-limit** [comment]
Aquest error es produeix quan l'expedient conté documents als quals se'ls ha esborrat el document definit a la definició de procés o tipus d'expedient i queden sense informació de document.
![image](https://user-images.githubusercontent.com/17267008/95593557-26381780-0a4a-11eb-9c57-9bcbc96dba24.png)
Es mou a la versió 3.2.110
