### ISSUE TITLE
Error en la consulta a domini intern

### ISSUE THREAD

**Issue by josepg-limit** [GovernIB/helium#883]
Realitzant proves a Preproducció s'ha produït l'error:

No s'ha trobat l'objecte de tipus (Domini) amb identificador (intern).

**Comment by josepg-limit** [comment]
S'han revisat els logs sense trobar cap referència a l'error reportat. Posteriorment em vist que els logs no corresponien a l'entorn de preproducció.

Al obtenir els logs de pre producció hem trobat l'error:
*`2016-08-10 08:51:52,339 ERROR [net.conselldemallorca.helium.ws.tramitacio.TramitacioServiceImpl] (http-10.215.9.184-58080-2) No s'ha pogut executar l'acció
net.conselldemallorca.helium.v3.core.api.exception.TramitacioHandlerException:  ===> Error en l'execució del Handler. Error al executa l'acció 'iniciarExploracio': Error al executar un handler de l'expedient (expedientId=39200, expedientTipusId=452, processInstanceId=46627137, taskInstanceId=null, tokenId=null). PID: 46627137. Handler: org.jbpm.graph.node.TaskNode. Mètode: execute. Fitxer: TaskNode.java. Num. línea: 174.No s'ha trobat l'objecte de tipus (Domini) amb identificador (intern) entornID: 50. entornCodi: CONAFESOC. entornNom: Expedients de Salut, Família i Serveis Socials. expedientID: 39200. expedientNumero: 07/1000020-M/16. expedientTipusID: 452. expedientTipusCodi: SISDEPEN_DIS. expedientTipusNom: Expedient de discapacitat CAIB.
        at net.conselldemallorca.helium.core.model.service.ExpedientService.executarAccio(ExpedientService.java:2104)
        at net.conselldemallorca.helium.core.model.service.ExpedientService$$FastClassBySpringCGLIB$$7b679b9d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:700)`*

Un cop identificat el problema només ha calgut crear el domini amb codi intern a l'entorn. No ha estat necessari modificar codi.
